exclude:
    (?x)^(
        lib/|
        notebooks/|
        tests/
    )

repos:
-  repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v{{ cookiecutter.precommit_version }}
   hooks:
   -  id: check-merge-conflict
   -  id: check-yaml

-   repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.4
    hooks:
    -   id: check-azure-pipelines
    -   id: check-github-workflows
    -   id: check-jsonschema
        name: validate pyproject.toml
        files: ^pyproject\.toml$
        types: [toml]
        args: ["--schemafile", "https://json.schemastore.org/pyproject.json"]
    -   id: check-jsonschema
        name: check azureml environment schemas
        files: environment.yml
        args: ["--schemafile", "https://azuremlschemas.azureedge.net/latest/environment.schema.json"]
    -   id: check-jsonschema
        name: check azureml component schemas
        files: component.yml
        args: ["--schemafile", "https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json"]
    -   id: check-jsonschema
        name: check azureml pipeline schemas
        files: pipeline_job.yml
        args: ["--schemafile", "https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json"]
    # looks like there is an error in the microsoft schema
    # create_job property not allowed, but it is a crucial part, also according to all other documentation
    # -   id: check-jsonschema
    #     files: schedule.yml
    #     args: ["--schemafile", "https://azuremlschemas.azureedge.net/latest/schedule.schema.json"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
    -   id: mypy
        args: [--config-file=./pyproject.toml]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
    -   id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [--config=./pyproject.toml]
    -   id: ruff-format
        types_or: [ python, pyi, jupyter ]
        args: [--config=./pyproject.toml]