parameters:
- name: python_version
  type: string
- name: poetry_version
  type: string
- name: organisation_name
  type: string
- name: devops_project
  type: string
- name: package_feed
  type: string
- name: feed_view
  type: string
- name: pat_username
  type: string
- name: pat
  type: string

steps:

  - template: configure_python.yml
    parameters:
      python_version: '${{ parameters.python_version }}'
      poetry_version: '${{ parameters.poetry_version }}'
      pat_username: '${{ parameters.pat_username }}'
      pat: '${{ parameters.pat }}'

  - script: poetry install --only build
    displayName: 'Install build dependencies with poetry'

  - script: |
      set -e

      version_toml=$(poetry run tomlq -r '.project.version' pyproject.toml)
      echo "Version number in pyproject.toml: $version_toml"
      echo "##vso[task.setvariable variable=version_toml]$version_toml"

      name_toml=$(poetry run tomlq -r '.project.name' pyproject.toml)
      normalised_name=$(echo "$name_toml" | tr '[:upper:]' '[:lower:]' | sed 's/[^[:alnum:]]/-/g')
      echo "Package name in pyproject.toml (normalised): $normalised_name"
      echo "##vso[task.setvariable variable=normalised_name]$normalised_name"

      package_id=$(curl -s -u :$(System.AccessToken) \
        "https://feeds.dev.azure.com/${{ parameters.organisation_name }}/${{ parameters.devops_project }}/_apis/packaging/Feeds/${{ parameters.package_feed }}/packages?api-version=7.1-preview.1" \
        | jq -r ".value[] | select(.name == \"$normalised_name\") | .id")

      echo "Package ID: $package_id"
      echo "##vso[task.setvariable variable=package_id]$package_id"
    displayName: "Get version number, package name, package id"

  - script: |
      set -e
      poetry build
    displayName: 'Build distribution'

  - task: TwineAuthenticate@1
    inputs:
      artifactFeed: ${{ parameters.devops_project }}/${{ parameters.package_feed }}
    displayName: 'Authenticate with Azure Artifacts'

  - script: |
      set -e

      if [[ -z "$package_id" ]]; then
        echo "##vso[task.logissue type=warning]Package does not exist in feed. Uploading new package."
      else
        echo "Package exists in feed with ID: $package_id"
      fi

      echo "Uploading wheel to Azure Artifacts feed..."
      poetry run twine upload \
        -r "${{ parameters.package_feed }}" \
        --config-file "$(PYPIRC_PATH)" \
        dist/*.whl \
        --verbose
    displayName: "Publish package to Artifacts feed"


  # promote when version does not exist in specified view yet
  - script: |
      curl -X 'PATCH' "https://pkgs.dev.azure.com/${{ parameters.organisation_name }}/${{ parameters.devops_project }}/_apis/packaging/feeds/${{ parameters.package_feed }}/PyPI/packages/$(normalised_name)/versions/$(version_toml)?api-version=7.1-preview.1" -H 'Content-Type: application/json' -u :$(System.AccessToken) -d "{\"views\": {\"op\": \"add\", \"path\": \"/views/-\", \"value\": \"${{ parameters.feed_view }}\"}}"
    displayName: "Promote package to view '${{ parameters.feed_view }}'"
