parameters:
  - name: python_version
    type: string
  - name: poetry_version
    type: string
  - name: package_name
    type: string
  - name: devops_organisation
    type: string
  - name: devops_project
    type: string
  - name: package_feed
    type: string

trigger: none

pr:
  branches:
    include:
      - "*"

variables:
  # PR target checks
  - name: toMain
    value: $[eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/main')]

  - name: toDev
    value: $[eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/develop')]

  # Determine feed view at runtime (prod for main, dvlm otherwise)
  - name: feed_view
    value: $[replace(replace(eq(variables['toMain'], true), True, 'prod'), False, 'dvlm')]

stages:

- stage: PreCommit
  displayName: Pre-commit checks
  dependsOn: []
  jobs:
    - job: ExecutePreCommit
      steps:
        - template: pre_commit.yml
          parameters:
            python_version: ${{ parameters.python_version }}
            poetry_version: ${{ parameters.poetry_version }}
            pat_username: $(PatUsername)
            pat: $(DevOpsPAT)

- stage: UnitTest
  displayName: Unit tests
  dependsOn: []
  jobs:
    - job: ExecuteUnitTests
      steps:
        - template: test.yml
          parameters:
            python_version: ${{ parameters.python_version }}
            poetry_version: ${{ parameters.poetry_version }}
            pat_username: $(PatUsername)
            pat: $(DevOpsPAT)
            package_name: ${{ parameters.package_name }}

- stage: Check
  displayName: Staging checks
  dependsOn: []
  condition: or(eq(variables.toMain, true), eq(variables.toDev, true))
  jobs:
    - job: Check
      variables:
        build: false
      steps:
        - template: build.yml
          parameters:
            python_version: ${{ parameters.python_version }}
            poetry_version: ${{ parameters.poetry_version }}
            organisation_name: ${{ parameters.devops_organisation }}
            devops_project: ${{ parameters.devops_project }}
            package_feed: ${{ parameters.package_feed }}
            feed_view: $(feed_view)
            pat_username: $(PatUsername)
            pat: $(DevOpsPAT)
