parameters:
  - name: package_name
    type: string
  - name: pythonVersion
    type: string
  - name: poetryVersion
    type: string
  - name: devops_organisation
    type: string
  - name: devops_project
    type: string
  - name: package_feed
    type: string
  - name: feed_view
    type: string
  - name: PatUsername
    type: string
  - name: DevOpsPAT
    type: string
stages:

- stage: PreCommit
  displayName: Pre-commit checks
  dependsOn: [] 
  jobs:
    - job: ExecutePreCommit
      steps:
        - template: pre_commit.yml
          parameters:
            python_version: ${{ parameters.pythonVersion }}
            poetry_version: ${{ parameters.poetryVersion }}
            pat_username: ${{ parameters.PatUsername }}
            pat: ${{ parameters.DevOpsPAT }}

- stage: UnitTest
  displayName: Unit tests
  dependsOn: [] 
  jobs:
    - job: ExecuteUnitTests
      steps:
        - template: test.yml
          parameters:
            python_version: ${{ parameters.pythonVersion }}
            poetry_version: ${{ parameters.poetryVersion }}
            package_name: ${{ parameters.package_name }}
            pat_username: ${{ parameters.PatUsername }}
            pat: ${{ parameters.DevOpsPAT }}

- stage: Check
  displayName: Staging checks
  dependsOn: [] 
  condition: or(   eq(variables['isDev'], true),   eq(variables['isMain'], true)    )
  jobs:
    - job: Check
      variables:
          build: false
      steps:
        - template: build.yml
          parameters:
            python_version: ${{ parameters.pythonVersion }}
            poetry_version: ${{ parameters.poetryVersion }}
            organisation_name: ${{ parameters.devops_organisation }}
            devops_project: ${{ parameters.devops_project }}
            package_feed: ${{ parameters.package_feed }}
            feed_view: ${{ parameters.feed_view }}
            pat_username: ${{ parameters.PatUsername }}
            pat: ${{ parameters.DevOpsPAT }}
