parameters:
- name: package_name
  type: string
- name: python_version
  type: string
- name: poetry_version
  type: string
- name: organisation_name
  type: string
- name: devops_project
  type: string
- name: package_feed
  type: string
- name: feed_view
  type: string
- name: pat_username
  type: string
- name: pat
  type: string
- name: toMain
  type: boolean
- name: toDev
  type: boolean

stages:

- stage: PreCommit
  displayName: Pre-commit checks
  dependsOn: [] 
  jobs:
    - job: ExecutePreCommit
      steps:
        - template: pre_commit.yml
          parameters:
            python_version: ${{ parameters.python_version }}
            poetry_version: ${{ parameters.poetry_version }}
            pat_username: ${{ parameters.pat_username }}
            pat: ${{ parameters.pat }}

- stage: UnitTest
  displayName: Unit tests
  dependsOn: [] 
  jobs:
    - job: ExecuteUnitTests
      steps:
        - template: test.yml
          parameters:
            package_name: ${{ parameters.package_name }}
            python_version: ${{ parameters.python_version }}
            poetry_version: ${{ parameters.poetry_version }}
            pat_username: ${{ parameters.pat_username }}
            pat: ${{ parameters.pat }}

- stage: Check
  displayName: Staging checks
  dependsOn: [] 
  condition: ${{ or(parameters.toMain, parameters.toDev) }}
  jobs:
    - job: Check
      variables:
        build: false
      steps:
        - template: build.yml
          parameters:
            python_version: ${{ parameters.python_version }}
            poetry_version: ${{ parameters.poetry_version }}
            organisation_name: ${{ parameters.organisation_name }}
            devops_project: ${{ parameters.devops_project }}
            package_feed: ${{ parameters.package_feed }}
            feed_view: ${{ parameters.feed_view }}
            pat_username: ${{ parameters.pat_username }}
            pat: ${{ parameters.pat }}
