
parameters:
- name: python_version
  type: string
- name: uv_version
  type: string

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '${{ parameters.python_version }}'
    displayName: 'Use Python ${{ parameters.python_version }}'
  - bash: |
        python -m pip install --upgrade pip
        python -m pip install uv==${{ parameters.uv_version }}
    displayName: 'Install uv ${{ parameters.uv_version }}'
