variables:
  - template: /devops_pipelines/templates/config.yml
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  - name: isDev
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]
  - name: PublishPackage
    value: True

stages:
  - stage: cookiecutter_self
    jobs:
      - job: self_precommit
        displayName: 'Validate YAML files and check for merge conflicts'
        steps:
          - checkout: self
            path: $(project_name)
          - template: /devops_pipelines/templates/pre_commit.yml
      - job: check_version
        displayName: 'Check if the Raptor version specified in pyproject.toml is still available'
        steps:
          - checkout: self
            persistCredentials: true
          - script: |
              set -e
              RELEASE_VERSION=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml','rb'))['project']['version'])")
              echo "Checking availability of version $RELEASE_VERSION"..
    
              if git ls-remote --tags --exit-code origin "refs/tags/$RELEASE_VERSION" >/dev/null 2>&1; then
                echo "ERROR: Git tag '$RELEASE_VERSION' already exists on origin."
                exit 1
              fi
              echo "OK: Version $RELEASE_VERSION is available"

  - stage: cookiecutter_package
    jobs:
      - job: package_pipeline
        displayName: 'Call cookiecutter on package_repo and run pre-commit'
        steps:
          - checkout: self
            path: $(project_name)
          - template: /devops_pipelines/templates/create_and_check_package_repo.yml

  - stage: cookiecutter_project
    jobs:
      - job: project_pipeline
        displayName: 'Call cookiecutter on project_repo and run pre-commit'
        steps:
          - checkout: self
            path: $(project_name)
          - template: /devops_pipelines/templates/create_and_check_project_repo.yml

  - stage: cookiecutter_tag
    dependsOn: cookiecutter_self
    condition: >
      and(
        succeeded(),
        variables.isDev,
        gt(variables['Build.SourceVersionParentsCount'], 1)
      )
    jobs:
      - job: tag_release
        displayName: 'Tagging the merge commit associated with the latest PR merge'
        steps:
          - checkout: self
            persistCredentials: true
          - script: |
              set -e
              RELEASE_VERSION=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml','rb'))['project']['version'])")
              git tag -a "$RELEASE_VERSION" "$(variables['Build.SourceVersion'])" -m "$(variables['Build.SourceVersionMessage'])"
              git push origin "$RELEASE_VERSION"