{% raw %}
$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: {% endraw %}{{cookiecutter.repo_name}}{% raw %}-deployment
endpoint_name: {% endraw %}{{cookiecutter.repo_name}}{% raw %}-online
model: azureml:{% endraw %}{{cookiecutter.repo_name}}{% raw %}:1
code_configuration:
  code: ../../components/package_c
  scoring_script: package_c_script.py
environment: 
  conda_file: ../../components/package_c/package_c_env.yml
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
instance_type: Standard_DS3_v2
instance_count: 1
app_insights_enabled: true
egress_public_network_access: disabled
{% endraw %}