
variables:
  pythonVersion: {{cookiecutter.python_version}}
  uvVersion: {{cookiecutter.uv_version}}
  pre_commit_version: 2.19.0
  devops_organisation: {{cookiecutter.organisation_name}}
  devops_project: {{cookiecutter.project_name}}
  sh_agent_pool_name: {{cookiecutter.private_agent_name}}
  # Create booleans for branches we want to build.
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]
