{% raw %}
$schema: https://azuremlschemas.azureedge.net/latest/batchDeployment.schema.json
name: {% endraw %}{{cookiecutter.repo_name}}{% raw %}-pipeline-deployment
endpoint_name: {% endraw %}{{cookiecutter.repo_name}}{% raw %}-batch
type: pipeline
component: batch-pipeline.yml
{% endraw %}