{% raw %}
name: Continuous Deployment

on:
  push: 
    branches: [main]

env: 
  PYTHON_VERSION: {% endraw %}{{cookiecutter.python_version}}{% raw %}

permissions:
  id-token: write
  pages: write
  contents: read

jobs:
  github-pages:
    uses: GemeenteRotterdam/raptor/templates/github/gh-pages.yml@main
    with:
      python_version: ${{ env.PYTHON_VERSION }}
{% endraw %}
