{% raw %}
name: {% endraw %}{{cookiecutter.package_name}}{% raw %} CICD

env:
  PROJECT_NAME: {% endraw %}{{cookiecutter.project_name}}{% raw %} # set this to your project name
  PYTHON_VERSION: {% endraw %}{{cookiecutter.python_version}}{% raw %} # set this to the Python version to use
  PACKAGE_NAME: {% endraw %}{{cookiecutter.package_name}}{% raw %} # set this to the name of Github environment
  AML_ENVIRONMENT: {% endraw %}{{cookiecutter.package_name}}{% raw %} # set this to the name of AML environment to create
  RG_NAME: {% endraw %}{{cookiecutter.azure_resource_group}}{% raw %} # set this to your Azure resource group name
  WS_NAME: {% endraw %}{{cookiecutter.azureml_workspace}}{% raw %} # set this to your Azure ML workspace name
  PUBLISH_ON_PYPI: {% endraw %}{{cookiecutter.publish_package_on_public_pypi}}{% raw %}

on:
  push:
    branches:
      - develop
      - main
      - release/*

  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Precommit:
    uses: GemeenteRotterdam/raptor/templates/github/pre_commit.yml@main
    with: 
      PYTHON_VERSION: ${{ env.PYTHON_VERSION }}

  UnitTest: 
    uses: GemeenteRotterdam/raptor/templates/github/unit_test.yml@main
    with: 
      PYTHON_VERSION: ${{ env.PYTHON_VERSION }}
      PACKAGE_NAME: ${{ env.PACKAGE_NAME }}

  Check: 
    needs: [Precommit, UnitTest]
    uses: GemeenteRotterdam/raptor/templates/github/unit_test.yml@main

  # https://stackoverflow.com/questions/59882715/use-environment-variable-in-github-action-if
  Build:
    if: ${{ env.PUBLISH_ON_PYPI }} == 'True' && needs.Check.outputs.src_changed == 'True'
    needs: [Check]
    uses: GemeenteRotterdam/raptor/templates/github/build.yml@main

  Register: 
    if:  ${{ env.REGISTER_AML_ENV }} == 'True' && success() && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release'))
    needs: [Build]
    uses: GemeenteRotterdam/raptor/templates/github/register.yml@main
    with: 
      AML_ENVIRONMENT: ${{ env.AML_ENVIRONMENT }}
      RG_NAME: ${{ env.RG_NAME }}
      WS_NAME: ${{ env.WS_NAME }}

  Documentation: 
    if: success() && github.ref == 'refs/heads/main'
    uses: GemeenteRotterdam/raptor/templates/github/documentation.yml@main
    with: 
      PYTHON_VERSION: ${{ env.PYTHON_VERSION }}
  
{% endraw %}