name: Build and publish to PyPI

on: 
  workflow_call:
    inputs:
      PYTHON_VERSION: 
        required: true
        type: string
      PACKAGE_NAME: 
        required: true
        type: string
      PROJECT_NAME: 
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest

    # # Dedicated environments with protections for publishing are strongly recommended.
    environment:
      name: ${{ env.PACKAGE_NAME }}
      url: https://pypi.org/p/${{ env.PROJECT_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python - -y
  
      - name: Update PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
  
      - name: Update Poetry configuration
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install --sync --no-interaction

      - name: Package project
        run: poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1