{% raw %}
trigger: none

pr:
  branches:
    include:
      - "*"

variables:
  # Load shared config
  - template: config.yml

  # PR target checks
  - name: toMain
    value: $[eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/main')]

  - name: toDev
    value: $[eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/develop')]

  # Determine feed view at runtime (prod for main, dvlm otherwise)
  - name: feed_view
    value: $[replace(replace(eq(variables['toMain'], true), True, 'prod'), False, 'dvlm')]

resources:
  repositories:
    - repository: raptor
      name: municipality-of-rotterdam/raptor
      type: github
      ref: tags/{% endraw %}{{cookiecutter.__cookiecutter_template_version}}{% raw %}
      endpoint: {% endraw %}{{ cookiecutter.github_service_connection }}{% raw %}

stages:

- stage: PreCommit
  displayName: Pre-commit checks
  dependsOn: [] 
  jobs:
    - job: ExecutePreCommit
      steps:
        - template: .azuredevops/templates/pre_commit.yml@raptor
          parameters:
            python_version: ${{ variables.pythonVersion }}
            poetry_version: ${{ variables.poetryVersion }}
            pat_username: $(PatUsername)
            pat: $(DevOpsPAT)

- stage: UnitTest
  displayName: Unit tests
  dependsOn: [] 
  jobs:
    - job: ExecuteUnitTests
      steps:
        - template: .azuredevops/templates/test.yml@raptor
          parameters:
            python_version: ${{ variables.pythonVersion }}
            poetry_version: ${{ variables.poetryVersion }}
            pat_username: $(PatUsername)
            pat: $(DevOpsPAT)
            package_name: {% endraw %}{{ cookiecutter.package_name }}{% raw %}

- stage: Check
  displayName: Staging checks
  dependsOn: [] 
  condition: or(eq(variables.toMain, true), eq(variables.toDev, true))
  jobs:
    - job: Check
      variables:
        build: false
      steps:
        - template: .azuredevops/templates/build.yml@raptor
          parameters:
            python_version: ${{ variables.pythonVersion }}
            poetry_version: ${{ variables.poetryVersion }}
            organisation_name: ${{ variables.devops_organisation }}
            devops_project: ${{ variables.devops_project }}
            package_feed: ${{ variables.package_feed }}
            feed_view: $(feed_view)
            pat_username: $(PatUsername)
            pat: $(DevOpsPAT)
{% endraw %}