
variables:
  package_name: {{cookiecutter.package_name}}

  # Python and poetry versions
  pythonVersion: {{cookiecutter.python_version}}
  poetryVersion: {{cookiecutter.poetry_version}}

  # Devops configuration
  devops_organisation: {{cookiecutter.organisation_name}}
  devops_project: {{cookiecutter.project_name}}
  package_feed:  {{cookiecutter.package_feed}}
  
  # Whether to register environment in Azure Machine Learning based on package
  RegisterAmlEnv: {{cookiecutter.create_aml_environment_in_cicd}}
  aml_environment: {{cookiecutter.package_name}}
  sh_agent_pool_name: {{cookiecutter.private_agent_name}}
  base_image: mcr.microsoft.com/azureml/openmpi5.0-ubuntu24.04

  # branch to read the documentation files from
  docsBranch: 'refs/head/generated/docs'
