{% raw %}
variables:
  pythonVersion: {% endraw %}{{cookiecutter.python_version}}{% raw %}
  poetryVersion: {% endraw %}{{cookiecutter.poetry_version}}{% raw %}
  devops_organisation: {% endraw %}{{cookiecutter.organisation_name}}{% raw %}
  devops_project: {% endraw %}{{cookiecutter.project_name}}{% raw %}
  
  # Name of artifacts feed
  package_feed:  {% endraw %}{{cookiecutter.package_feed}}{% raw %}
  
  # Whether to register environment in Azure Machine Learning based on package
  RegisterAmlEnv: {% endraw %}{{cookiecutter.create_aml_environment_in_cicd}}{% raw %}
  aml_environment: {% endraw %}{{cookiecutter.package_name}}{% raw %}
  sh_agent_pool_name: {% endraw %}{{cookiecutter.private_agent_name}}{% raw %}
  base_image: mcr.microsoft.com/azureml/openmpi5.0-ubuntu24.04

  # branch to read the documentation files from
  docsBranch: 'refs/head/generated/docs'
{% endraw %}